# Generated by Django 5.1.4 on 2025-01-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('bomba_opcao', models.CharField(blank=True, choices=[('choppeira_eletrica', 'Choppeira Elétrica'), ('choppeira_bomba', 'Choppeira Bomba')], max_length=20, null=True, verbose_name='Escolha uma opção')),
                ('profissional', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], default='dinheiro', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plataforma.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EventoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.evento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.produto')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='produtos',
            field=models.ManyToManyField(related_name='eventos', through='plataforma.EventoProduto', to='plataforma.produto'),
        ),
    ]
