# Generated by Django 5.1.4 on 2025-01-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('endereco_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('chopp_quantidade_marca', models.CharField(help_text='Informe a quantidade e marca do chopp.', max_length=255)),
                ('bomba_opcao', models.CharField(blank=True, choices=[('bomba_eletrica', 'Bomba Elétrica'), ('profissional', 'Profissional')], max_length=20, null=True, verbose_name='Escolha uma opção')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], default='dinheiro', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
