# Generated by Django 5.1.4 on 2025-01-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Contrato')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Contrato')),
                ('arquivo', models.FileField(upload_to='contratos_padroes/', verbose_name='Arquivo do Contrato Padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
    ]
